version: '3.8'

services:

  mysqldb:
    image: mysql:8.0  
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: nextclouddb1
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: pass123
    volumes:
      - db_data:/var/lib/mysql #cuva logove u volume-u
    networks:
      - nextcloud_network

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: pass123
      MYSQL_DATABASE: nextclouddb1
      MYSQL_HOST: mysqldb
    volumes:
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
    ports:
      - "8082:80"
    restart: unless-stopped
    depends_on:
      - mysqldb
    networks:
      - nextcloud_network
      
  proxy:
    image: nginx:latest
    container_name: proxy
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - nextcloud
    networks:
      - nextcloud_network

  

volumes:
  db_data:
  nextcloud_config:
  nextcloud_data:

networks:
  nextcloud_network:
